### ISSUE TITLE
viewDidLoad问题

### ISSUE THREAD

**Issue by XYXiaoYuan** [Chris-Pan/JPNavigationController#1]
iOS对于UITabBarController上的UIViewController是延迟调用viewDidLoad的，即用户点击之后才调用这个方法。使用JPNavigationController之后，打开APP时会立即触发所有的UIViewController的viewDidLoad方法，这样可能会导致一些意想不到的结果。tabBar上的三个控制器竟然不是懒加载进去的,一启动tabBar上的三个控制器直接都调用了viewDidLoad方法

**Comment by Chris-Pan** [comment]
上个版本使用类工厂方法,在类工厂方法里操作了用户传进来的控制器的View,所以会造成在应用启动的时候TabBarVC的子控制器一起加载,有性能问题.这次提交修复了这个问题, TabBarVC的子控制器都能遵循懒加载的原则.谢谢您提出的宝贵意见,祝您玩的开心.
