### ISSUE TITLE
发现在远程推送跳转时出现导航栏隐藏和tabBar显示的bug

### ISSUE THREAD

**Issue by miwerBean** [Chris-Pan/JPNavigationController#3]
远程推送时在点击推送时进行push, 过程是先获取当前根控制器的导航栏, 再进行跳转. 真机测试发现跳转时并没有走重写的 - (void)pushViewController:(nonnull UIViewController *)viewController animated:(BOOL)animated 这个方法

**Comment by Chris-Pan** [comment]
我的项目里也使用了远程通知, 没有出现你所描述的问题, 能不能先排查一下你自己的代码呢? 希望能帮到你.

**Comment by miwerBean** [comment]
BYTabBarController * tabVc = (BYTabBarController *)self.window.rootViewController;
    BYNavigationController * currentNavi = (BYNavigationController *)tabVc.viewControllers[tabVc.selectedIndex];
    [currentNavi pushViewController:[[BYAlarmPositionController alloc] init] animated:YES];

我是这样跳转的, 能帮我看下这样有问题吗, 这样跳过去是没有走重写的push方法,所以出现了我上面说的那种bug

**Comment by Chris-Pan** [comment]
你的那条评论, 我在github上看不到, 我只收到了github发给我的邮件, 你的问题可能出在拿导航控制器的时候, 拿到的是nil, 你打印看一下, 如果有问题, 你在微信上联系我把allen910818

**Comment by miwerBean** [comment]
哦  那个问题已经解决了  是我导航栏取错了   谢谢哈
