### ISSUE TITLE
奔溃啦

### ISSUE THREAD

**Issue by wangsujin2015** [Chris-Pan/JPNavigationController#4]
//返回的时候这里崩溃

-(CGFloat)jp_interactivePopMaxAllowedInitialDistanceToLeftEdge{
#if CGFLOAT_IS_DOUBLE
    return [objc_getAssociatedObject(self, _cmd) doubleValue];
#else
//模拟器在这里崩溃
    return [objc_getAssociatedObject(self, _cmd) floatValue];
#endif
}

**Comment by Chris-Pan** [comment]
堆栈信息能给我看一下吗?

**Comment by Chris-Pan** [comment]
堆栈信息能给我看一下吗?

**Comment by wangsujin2015** [comment]
您的demo runtime 部分  ,建议 您用不同真机和 模拟器 测下.....很容崩溃. 很喜欢这个kit

**Comment by Chris-Pan** [comment]
谢谢你的建议, 在Xcode 8.2 和 iOS10.2之前都有测试过真机和模拟器, 今天下载了最新的Xcode 8.2 和 iOS10.2, 运行时确实有你所碰到的问题, 大概会在这个周末适配最新的系统版本.

**Comment by Chris-Pan** [comment]
你提交的问题已经修复了, 具体请参看 https://github.com/Chris-Pan/JPNavigationController/releases/tag/1.2.1
