### ISSUE TITLE
导航条的问题

### ISSUE THREAD

**Issue by lly4155** [Chris-Pan/JPNavigationController#6]
大神好，我最近想用你写的全屏左滑控制器的轮子。但是用在我的项目里有一个让我很头疼的BUG，一直没找出原因。就是我的主控制器初始化显示的时候，导航条的标题，左右item按钮都是我设计的样子，但是进入下一个控制器然后pop回来的时候，导航条的显示就都没了，左边的按钮也变成了你写的默认返回按钮图标了。求大神解析~谢谢

**Comment by Chris-Pan** [comment]
试试在 ViewWillAppear 方法里条用设置导航栏的代码, 这个 bug 只会在 iOS10 上才有, 可以能使苹果改了一些条用 view 方法的原理造成的.

**Comment by lly4155** [comment]
还是不行，一样的效果。另外还有个BUG就是关于左滑指定控制器的代理不响应，完全按照你的demo写，但在我这边就是不执行。。小白一枚，是哪里设置要改吗？有点摸不清头脑了~

**Comment by lly4155** [comment]
左滑的代码，我大概是这么写的，先导入头文件，然后<jp……delegate>，再在viewdidload设置代理 = self。然后实现代理的push方法，创建指定控制器，然后正常push

**Comment by Chris-Pan** [comment]
按照你的写法写个demo给我.

**Comment by lly4155** [comment]
我刚模块测试了，问题出在我的问题~我push的控制器的init是传URL，但是不是HTTPS的就不能那么直接打开，只能系统的push才行。但是还是之前那个问题，这样的话返回，主页面的导航条还是没了

**Comment by Chris-Pan** [comment]
好的，解决了就好。我关闭问题了。
