### ISSUE TITLE
push到new tabbarcontroller中之后之前隐藏的navbar出现了 侧滑返回正常，点击返回会返回到最初的nav中

### ISSUE THREAD

**Issue by xiaoyishan** [Chris-Pan/JPNavigationController#8]
用push因为遮罩动画要用到转场和Navdelegate
看来以后直接Root tabbarcontroller比较简单无烦恼

**Comment by Chris-Pan** [comment]
UINavigationBar 在项目中是为每个 控制器定制的，所以应该不会有你说的这种情况，可能我没有理解你的问题，不好意思。
