### ISSUE TITLE
左滑push下一个vc的手势失效情况求解

### ISSUE THREAD

**Issue by DarrenXman** [Chris-Pan/JPNavigationController#9]
ViewController.m的viewDidLoad里
self.tableView.contentInset = UIEdgeInsetsMake(headerHeight, -40, 0, 40);  左边距大雨-40左滑push失效，不太清楚到底为什么会这样，难道contentInset影响手势响应？请教大神

**Comment by Chris-Pan** [comment]
是的，是因为你水平插入了一个额外滚动距离导致水平滑动手势被 UITableView 实例拦截了，如果是这种情况，你可能需要自己继承 UITableView 并实现 hitTest 方法来应对了。希望能帮到你。
